name: Azure CLI test

on:
  push:
    paths:
      - ".github/workflows/cli.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
            az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}
            az webapp deployment list-publishing-profiles --name devmemos --resource-group DevMemos >> publish.publishsettings

      - name: Prepare publish profile
        shell: bash
        run: |
          tr -d '\n' < publish.publishsettings >> publishsettings
          echo "::set-output name=publishsettings::$(cat publishsettings)"
        id: preparepublishprofile

      - name: Show publish profile
        shell: bash
        run: |
          echo "${{ steps.preparepublishprofile.outputs.publishsettings }}"
